language: python
python:
  - 2.6
  - 2.7
  # - 3.1
  - 3.2
  - 3.3
  - 3.5
  - 3.6-dev
  - nightly
  - pypy

env:
  - LMDB_FORCE_CFFI=1
  - 
install:
  - sudo apt-get install gdb
  - pip install cffi


  # this is a workaround for https://github.com/dw/py-lmdb/issues/132
  - git revert --no-commit 04ef5846262d9bee39938208af14cce28ebc1834

  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install -I py==1.4.20 pytest==2.5.2; fi
before_script:
  - source misc/helpers.sh
  
script:
  - > 
    if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; 
      then 
        sudo ./misc/runtests-travisci.sh 
      else 
        with_gdb python -m pytest tests; 
    fi

notifications:
  email: false
