language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"


install:
  - sudo apt-get install libffi-dev
  - pip install cffi --use-mirrors
  - pip install -e . --use-mirrors

script: ./runtests.sh

notifications:
  email: false
